#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime
# =============================================================================
# generate_structure.py - Codey Tools 
# Generates PROJECT_STRUCTURE.md with a visual repo tree.
# Respects .gitignore patterns + custom ignore list below.
# =============================================================================
# Codey is a neutral quality pet/tool for GitHub and GitLab.
# It shows the world that not everything is scam and AI-generated garbage.
# Codey scores Developer integrity — you can't fake it, you have to earn it.
#
# This tool is considered a security tool under ESOL v1.1:
# it audits developer behavior, code quality and social engineering patterns.
# Public audit available on GitHub — transparent, community-verified.
#
# Free to use on GitHub and GitLab.
# Selling this script or using it for reputation manipulation is prohibited.
#
# Licensed under Apache 2.0 + Ethical Security Operations License (ESOL v1.1)
# Jurisdiction: Germany (Berlin) — enforced under StGB §202a/b/c and DSGVO.
# https://github.com/VolkanSah/ESOL
#
# Copyright (c) 2026 VolkanSah & BadTin and some Cats 🐱
# =============================================================================
# Refactored + Bugs fixed + Issue analysis added
# BUG:      marks fixed bugs
# NEW:      marks new features
# IMPROVED: marks improvements
# =============================================================================

# ─────────────────────────────────────────────
# IGNORE LIST — folders/files to skip
# ─────────────────────────────────────────────
IGNORE = {
    '.git',
    '__pycache__',
    '.pytest_cache',
    '*.pyc',
    '.DS_Store',
    'node_modules',
    '.venv',
    'venv',
}

def is_ignored(path: Path) -> bool:
    name = path.name
    for pattern in IGNORE:
        if '*' in pattern:
            if path.match(pattern):
                return True
        elif name == pattern:
            return True
    return False


def generate_tree(root: Path, prefix: str = "", is_last: bool = True) -> list:
    lines = []
    connector = "└── " if is_last else "├── "

    # label
    if root == Path("."):
        label = root.resolve().name + "/"
        lines.append(label)
        children = sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        for i, child in enumerate(children):
            if is_ignored(child):
                continue
            lines.extend(generate_tree(child, prefix="", is_last=(i == len(children) - 1)))
        return lines

    if root.is_dir():
        lines.append(f"{prefix}{connector}{root.name}/")
        extension = "    " if is_last else "│   "
        children = sorted(root.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        visible  = [c for c in children if not is_ignored(c)]
        for i, child in enumerate(visible):
            lines.extend(generate_tree(child, prefix + extension, is_last=(i == len(visible) - 1)))
    else:
        lines.append(f"{prefix}{connector}{root.name}")

    return lines


def main():
    root    = Path(".")
    tree    = generate_tree(root)
    now     = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    output  = f"""# 📁 Project Structure

> Auto-generated by `generate_structure.py` — {now}
> Do not edit manually.

```
{"
".join(tree)}
```
"""

    out_path = Path("PROJECT_STRUCTURE.md")
    out_path.write_text(output, encoding="utf-8")
    print(f"✓ PROJECT_STRUCTURE.md written ({len(tree)} lines)")


if __name__ == "__main__":
    main()
