import json
import os
from datetime import datetime

def load_json(filename):
    if os.path.exists(filename):
        with open(filename, 'r') as f:
            return json.load(f)
    return {}

def generate_markdown():
    rate_limit = load_json('rate_limit.json')
    user_info = load_json('user_info.json')
    workflows = load_json('workflows.json')
    graphql = load_json('graphql_check.json')

    now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

    md_content = f"""# Codey Audit Report
Last Manual Update: {now}

---

## 🛡️ API Integrity & Limits
* **Core Limit:** {rate_limit.get('resources', {}).get('core', {}).get('limit')}
* **Core Remaining:** {rate_limit.get('resources', {}).get('core', {}).get('remaining')}
* **GraphQL Limit:** {rate_limit.get('resources', {}).get('graphql', {}).get('limit')}
* **GraphQL Remaining:** {rate_limit.get('resources', {}).get('graphql', {}).get('remaining')}

## 👤 Identity Verification
* **User:** {user_info.get('login')} (ID: {user_info.get('id')})
* **Type:** {user_info.get('type')}
* **Public Repos:** {user_info.get('public_repos')}

## ⚙️ Active Workflows
"""
    for wf in workflows.get('workflows', []):
        md_content += f"* **{wf['name']}**: State: `{wf['state']}` | Path: `{wf['path']}`\n"

    md_content += f"""
## 📊 Repository Insight (GraphQL)
* **Authenticated as:** {graphql.get('data', {}).get('viewer', {}).get('login')}
* **Disk Usage:** {graphql.get('data', {}).get('repository', {}).get('diskUsage')} KB
* **Stars:** {graphql.get('data', {}).get('repository', {}).get('stargazers', {}).get('totalCount')}

---
*Audit generated by Codey "No Mercy" Logic (ESOL v1.1)*
"""

    with open('AUDIT_DATA.md', 'w') as f:
        f.write(md_content)

if __name__ == "__main__":
    generate_markdown()
